label: Autority
description: 'Přidejte odkaz na https://powo.science.kew.org/ a IPNI identifikátor vložte jako text, který se má zobrazit (e.g. 731955-1) nebo vložte odkaz na českou databázi Pladias'
