label: 'Odkazy na podrobnější informace o tomto jednoduchém léčivu '
description: 'Přidejte odkaz na českou databázi Pladias https://pladias.cz/ nebo na Plants of the World https://powo.science.kew.org/ a na Atlas léčivých rostlin https://is.muni.cz/auth/do/med/el/lecive_rostliny/atlas.html'
