label: 'Moderní název jednoduchého léčiva'
settings:
  field_settings:
    plant:
      label: 'Moderní název jednoduchého léčiva'
    certainty:
      label: Jistota
    user:
      label: 'Identifikováno uživatelem'
    note:
      label: Poznámka
