title: 'Původ obrázku v banneru'
content:
  value: '<p><strong>Práva k úvodnímu obrázku</strong></p><p>Obrázek na domovské stránce platformy je z rukopisu <a href="//www.manuscriptorium.com/apps/index.php?direct=record&amp;pid=RTRBAR-NMP___I_H_29______42S6WYA-xx"><span>I H 29 (Národní knihovna České republiky)</span></a><span> a je vystavený pod licenci </span><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.cs">CC BY-NC-SA 4.0 DEED</a>.</p>'
  format: basic_html
