content:
  value: '<p><br><strong>Copyright</strong></p><p>Databáze Herbaria manuscripta Masarykovy University může být používána v souladu s podmínkami licence Creative Commons: <a href="https://creativecommons.org/licenses/by/4.0/deed.cs"><span>Creative Commons BY 4.0</span></a><span>.</span></p>'
  format: basic_html
