content:
  value: '<p><br><strong>Copyright</strong></p><p>Databáze Herbaria manuscripta Masarykovy University může být používána v souladu s podmínkami licence Creative Commons: <a href="https://creativecommons.org/licenses/by/4.0/deed.cs"><span>CC BY 4.0</span></a>.</p><p><a href="https://creativecommons.org/licenses/by/4.0/deed.cs" target="_blank"><img src="/themes/custom/islandora_muni/images/by.svg" alt="CC BY" width="120" height="42"></a></p>'
  format: full_html
