content:
  value: '<p><strong>Poděkování</strong></p><p>Dataset vznikl v rámci projektu <a href="https://www.phil.muni.cz/vyzkum/resene-projekty/47246"><span>MUNI/G/1059/2018</span></a> <em><span>Herbaria manuscripta Bohemiae et Moraviae usque ad annum 1500 – databáze rukopisných herbářů do roku 1500 jako platforma ke studiu humanitních i přírodovědných disciplín (Herbaria manuscripta), který byl realizován v období</span></em><span lang="en"> březen </span><span>2019 až červen 2023.</span></p>'
  format: basic_html
title: Poděkování
