label: 'Kopie herbářů'
display:
  default:
    display_title: 'Kopie herbářů'
    display_options:
      title: 'Kopie textů'
      fields:
        field_work:
          label: Název
        field_manuscript:
          label: 'Signatura rukopisu'
        field_institution:
          label: 'Instituce a kolekce'
        field_herbal:
          label: 'Počet zpracovaných položek herbáře'
        field_city:
          label: Město
      exposed_form:
        options:
          submit_button: Odeslat
          reset_button_label: Resetovat
          exposed_sorts_label: 'Seřadit podle'
          sort_asc_label: vzestupně
          sort_desc_label: sestupně
          bef:
            filter:
              field_link_uri:
                advanced:
                  rewrite:
                    filter_rewrite_values: '- jakýkoliv -|Ne'
      use_more_text: více
      footer:
        result:
          content: 'Zobrazuje se @start až @end z @total výsledků vyhovujících podmínkám vyhledávání'
      filters:
        field_work_target_id:
          expose:
            label: Název
        title:
          expose:
            label: 'Signatura rukopisu'
        title_1:
          expose:
            label: 'Položky herbáře'
        field_herbal_target_id:
          expose:
            label: 'Má zpracované položky?'
          group_info:
            label: 'Zobrazit jen herbáře se zpracovanými položkami'
            group_items:
              1:
                title: Ne
              2:
                title: Ano
        field_city_target_id:
          expose:
            label: Město
        field_link_uri:
          group_info:
            label: 'Zobrazit jen výsledky s odkazem na digitalizovaný rukopis'
            group_items:
              1:
                title: Ano
          expose:
            label: Odkaz
        field_text_language_target_id:
          expose:
            label: Jazyk
        field_type_target_id_1:
          expose:
            label: Typ
      pager:
        options:
          tags:
            next: 'Další ›'
            previous: '‹ Předchozí'
            first: '« První'
            last: 'Poslední »'
      sorts:
        name:
          expose:
            label: názvu
        title:
          expose:
            label: rukopisu
        field_incipit_value:
          expose:
            label: incipitu
  herbaria_herbals:
    display_title: Stránka
    display_options:
      menu:
        title: Herbáře
