display:
  default:
    display_options:
      header:
        area:
          content:
            value: '<p>{% if field_citation %}<strong>Bibliografie</strong> (<strong>{{ type }})</strong>{% endif %}</p>'
            format: basic_html
