label: Rukopisy
display:
  default:
    display_options:
      title: Rukopisy
      header:
        result:
          content: '<h1>Rukopisy</h1>'
      pager:
        options:
          tags:
            next: 'Další ›'
            previous: '‹ Předchozí'
            first: '« První'
            last: 'Poslední »'
