display:
  default:
    display_options:
      title: Bibliografie
      pager:
        options:
          tags:
            next: 'Další ›'
            previous: '‹ Předchozí'
            first: '« První'
            last: 'Poslední »'
      fields:
        name:
          label: '• Odkazováno na z'
        title:
          label: '• Odkazováno na z'
