content:
  value: '<p>©&nbsp;<script>const datey = new Date(); document.write(datey.getFullYear());</script><span> </span><a href="https://muni.cz/">Masaryk University</a><br><a href="mailto:digitalia@phil.muni.cz">Webmaster</a> | <a class="mc-open-dialog" href="#">Cookies</a></p>'
  format: full_html
