status: 1
pattern: '[node:field_manuscript]: [node:field_work]'
escape: false
preserve_titles: false
save: true
chunk: 50
dependencies:
  config:
    - node.type.work_in_manuscript
new_content_behavior: 1
