features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: themes/islandora_muni/platform_specific/images/logo.svg
favicon:
  use_default: 0
  path: 'public://muni_favicon.ico'
  mimetype: image/vnd.microsoft.icon
