_core:
  default_config_hash: ZdPdgeYPxAPoTIlcCxW_tRoExm87onUdOjF3ZY2gfto
rest_oai_pmh:
  entity_type: node
view_displays:
  'oai_pmh:all_repository_items': 'oai_pmh:all_repository_items'
  'oai_pmh:collection_sets': 'oai_pmh:collection_sets'
  'oai_pmh:collectionless_set': 'oai_pmh:collectionless_set'
  'oai_pmh:text_in_manuscript': 'oai_pmh:text_in_manuscript'
support_sets: 1
mapping_source: rdf
repository_name: 'Herbaria manuscripta'
repository_email: digitalia@phil.muni.cz
expiration: '3600'
metadata_map_plugins:
  -
    label: oai_raw
    value: ''
  -
    label: oai_dc
    value: dublin_core_metatag
  -
    label: mods
    value: ''
cache_technique: liberal_cache
mods_view:
  view_machine_name: ''
  view_display_name: ''
