_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: cs
uuid: 86955ff9-1be3-40ad-84ae-414c65ae901c
name: 'Herbaria manuscripta'
mail: lindat-clariah@phil.muni.cz
slogan: ''
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
